version: '3'

services: 
  db:
    image: postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=licenses
      - POSTGRES_HOST=db

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8080
    volumes: 
      - .:/code
    ports:
      - '8080:8080'
    depends_on: 
      - db

volumes:
  postgres_data: